ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_NAME
ARG KAFKA_ENABLED

FROM gradle:8.7-jdk21 AS build
WORKDIR /home/gradle/genealogy-app/

COPY /gen-app/ .

RUN chown root gradlew \
    && chmod +x ./gradlew \
    && ./gradlew :back:controller:bootJar

FROM openjdk:21-jdk-slim AS run
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_NAME
ARG KAFKA_ENABLED

ENV POSTGRES_USER=${POSTGRES_USER} \
    POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    POSTGRES_HOST=${POSTGRES_HOST} \
    POSTGRES_PORT=${POSTGRES_PORT} \
    POSTGRES_NAME=${POSTGRES_NAME} \
    KAFKA_ENABLED=${KAFKA_ENABLED}

RUN adduser --system --group app-user && mkdir /app
COPY --from=build /home/gradle/genealogy-app/back/controller/build/libs/controller.jar /app/
EXPOSE 8080
USER app-user

CMD ["java", "-jar", "/app/controller.jar"]