version: "3.9"
services:
  back:
    container_name: back
    image: ghcr.io/realteazzer/genealogy-visualizer-back:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - gen-app-network    
  front:
    container_name: front
    image: ghcr.io/realteazzer/genealogy-visualizer-front:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - gen-app-network


networks:
  gen-app-network: