name: deploy back
on: workflow_dispatch

jobs:
    deploy-back:
    # The type of runner that the job will run on
        runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              path: 'deploy-files'
          - name: Login to GitHub Registry
            uses: docker/login-action@v1 
            with:
              registry: ghcr.io
              username: "realteazzer"
              password: ${{ secrets.REGISTRY_TOKEN }}
          - name: copy docker compose via ssh password
            uses: appleboy/scp-action@v0.1.7
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USERNAME }}
              password: ${{ secrets.SERVER_PASSWORD }}
              port: ${{ secrets.SERVER_PORT }}
              overwrite: true
              source: "./deploy-files/docker-compose-app-GA.yaml"
              target: ./gen-app/
              strip_components: 2   
          - name: "Run deploy on server"
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USERNAME }}
              password: ${{ secrets.SERVER_PASSWORD }}
              port: ${{ secrets.SERVER_PORT }}
              script: |
                  export CR_PAT=${{ secrets.REGISTRY_TOKEN }}
                  echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
                  docker compose -f ./gen-app/docker-compose-app-GA.yaml pull
                  docker compose -f ./gen-app/docker-compose-app-GA.yaml up back -d